JamesTKhan/Mundus

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableModelComponent.java, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableTerrainComponent.java, editor/src/main/com/mbrlabs/mundus/editor/tools/picker/GameObjectPicker.java, editor/src/main/com/mbrlabs/mundus/editor/tools/picker/ToolHandlePicker.java
This is the first baby step to make Scene to look more similar to gdx-gltf's [SceneManager](https://github.com/mgsx-dev/gdx-gltf/blob/master/gltf/src/net/mgsx/gltf/scene3d/scene/SceneManager.java).
=> Move model batch from sceneGraph to scene

editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/events/LogEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/UI.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/DockBar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/LogBar.kt
While working on Asset Deletion branch I needed an area to display informational messages and non-critical errors without spamming the user with dialogs. This PR adds a logging tab which you can add entries via:
`postEvent(new LogEvent("Message here"));`
=> Add a LogBar in the bottom dock

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainGenTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/generation/HeightmapTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/generation/PerlinNoiseTab.kt
I redesigned the terrain generation tab before I add it to the docs.
Here is the old design:
Here is the new design:
=> New terrain generation design

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/Outline.kt
Adds a double click action on game objects within the scene tree. When double (left) clicked the camera will look at that object. If its more than a certain distance away camera will do a basic lerp towards the target as well. Functionality is limited for now but may make it smarter about object size down the line.
=> Double clicking GameObject looks at object

commons/src/main/com/mbrlabs/mundus/commons/assets/TerrainAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaLoader.java, commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaTerrain.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/assets/MetaSaver.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainSettingsTab.kt
Add UV scale slider in the terrain settings tab that persists and is stored in MetaTerrain
https://user-images.githubusercontent.com/28971753/164090477-356712c9-e8f1-4d20-8d40-4a3a688c53c1.mp4
=> Add editable uv scale for terrains

commons/src/main/com/mbrlabs/mundus/commons/shaders/water.frag.glsl
Update water shader glsl code to support 1.10 for linux and mac.
=> Fix water shader compatability with glsl 1.10

commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaLoader.java, commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaWater.java, commons/src/main/com/mbrlabs/mundus/commons/shaders/WaterShader.java, commons/src/main/com/mbrlabs/mundus/commons/shaders/water.frag.glsl, commons/src/main/com/mbrlabs/mundus/commons/water/Water.java, commons/src/main/com/mbrlabs/mundus/commons/water/WaterFloatAttribute.java, editor/src/main/com/mbrlabs/mundus/editor/assets/MetaSaver.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/WaterWidget.kt
Specular highlight code for water was in place but it was not working. This PR fixes specular highlight for water, and makes reflectivity and shine damper attributes editable on water components.
https://user-images.githubusercontent.com/28971753/167267431-421854dc-8cac-440f-8146-df35e53aa451.mp4
=> Fix specular water

build.gradle
When I added the gltf library then there was not 2.x version but the 1.0.0 was a bit old. So I think better to use stable version instead of snapshot version.
=> Updated gltf version to 2.0.0-rc.1

README.md, commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/SkyboxDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/SkyboxBuilder.kt, gdx-runtime/CHANGES, gdx-runtime/build.gradle, gdx-runtime/src/com/mbrlabs/mundus/runtime/SceneLoader.java, gdx-runtime/src/com/mbrlabs/mundus/runtime/Shaders.java, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/SceneConverter.java
This PR includes the following:
- Update skyboxes in README
- Update changes files to catch up with 0.3.0
- Enable fog on runtime
- Enable support for skyboxes on runtime
- Update runtime to v0.3.0
Jitpack requires a release so the plan is to create a 0.3.0 release after this PR then look into JitPack implementation for the runtime
Screenshot of skybox and fog functioning in runtime
=> Runtime 0.3.0 and change log updates

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt
Small PR to add texture thumbnails to texture assets. The assets section has a long way to go, but this is a small step in improving it.
=> Add thumbnails for TextureAssets in asset dock

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/WaterComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/MundusMultiSplitPane.java, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/MundusSplitPane.java
Well I am happy! This took a few weeks to figure out but it turns out the odd rendering issue with Water (FBO's in general) when not in fullscreen is due to use of ScissorStack glScissors in the Mundus Splitpane classes. 
I have edited the classes to NOT perform glScissors on the RenderWidget. This appears to resolve the rendering issue and I am not seeing any negative impacts from the change. 
**Before fix:**
**After this fix:**
=> Fix water FBO rendering issue

commons/src/main/com/mbrlabs/mundus/commons/utils/MathUtils.java, commons/src/test/com/mbrlabs/mundus/commons/utils/MathUtilsTest.java, editor/src/main/com/mbrlabs/mundus/editor/tools/ScaleTool.java, editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java
I think a custom method is unnecessary if it is already in a library, so I replaced MathUtils.dst method to Vector2.dst method.
=> Replaced custom dist method to Vector2.dst method

gdx-runtime/src/com/mbrlabs/mundus/runtime/Mundus.java
A bit refactor.
I think with this changes who uses this runtime will have less chance of making mistakes.
Currently:
```
batch = new ModelBatch();
mundus = new Mundus(Gdx.files.internal("mundus"));
mundis.init();
scene = mundus.loadScene("Main Scene.mundus");
scene.batch = batch;
```
The developer can leave `init` method, or forget to set batch and these will generate exception.
With changes this is enough:
```
batch = new ModelBatch();
mundus = new Mundus(Gdx.files.internal("mundus"));
scene = mundus.loadScene("Main Scene.mundus", batch);
```
=> Refactored runtime's Mundus

build.gradle, commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/utils/GLUtils.java, commons/src/main/com/mbrlabs/mundus/commons/utils/NestableFrameBuffer.java, gdx-runtime/CHANGES, gdx-runtime/build.gradle
Set source compatibility to 1.7 for gdx-runtime, otherwise it seems it defaults to 1.8 with Jitpack which causes errors on clients using the runtime unless they also set to 1.8. 
Also, remove Guacamole library and bring the two classes we need from it adapted for 1.7 because Guacamole has 1.8 source compat.
=> Source Compatibility 1.7

gdx-runtime/README.md
I think after this PR (https://github.com/jpooleycodes/Mundus/pull/45) this readme is unnecessary.
=> Removed unnecessary readme

editor/src/main/com/mbrlabs/mundus/editor/tools/picker/BasePicker.java
This fixes an issue where mac computers with retina screens cannot use tool handles to manipulate game objects, the clicks are not detected. This appears to be related to HDPI and the framebuffer used to detect clicks on the tool handles. Implemented a fix using temporary Pixels HDPI mode when rendering to tool handle FBO as described in wiki: https://libgdx.com/wiki/graphics/opengl-utils/frame-buffer-objects
=> Fix tool handles not clicking on mac/retina screens

commons/src/main/com/mbrlabs/mundus/commons/assets/MaterialAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/TerrainAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaLoader.java, commons/src/main/com/mbrlabs/mundus/commons/assets/meta/MetaTerrain.java, commons/src/main/com/mbrlabs/mundus/commons/shaders/ModelShader.java, commons/src/main/com/mbrlabs/mundus/commons/shaders/TerrainShader.java, commons/src/main/com/mbrlabs/mundus/commons/shaders/model.frag.glsl, commons/src/main/com/mbrlabs/mundus/commons/shaders/model.vert.glsl, commons/src/main/com/mbrlabs/mundus/commons/shaders/terrain.frag.glsl, commons/src/main/com/mbrlabs/mundus/commons/shaders/terrain.vert.glsl, commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java, commons/src/main/com/mbrlabs/mundus/commons/terrain/TerrainTexture.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/MetaSaver.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainPaintTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/MaterialWidget.kt
Adds the ability to add normal maps to terrains via simplified UI for a considerable improvement on the look of terrains.
https://user-images.githubusercontent.com/28971753/176582752-ac910ab0-dfdd-43f1-9a1c-45473f632a79.mp4
https://user-images.githubusercontent.com/28971753/176691421-a945a4eb-f741-40a2-a7ba-c4ec44c80ed2.mp4
=> Add normal maps to terrains and models

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/FileMenu.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/Toaster.kt
Quick fix to get toast messages actually displaying as code already exists to do so.
=> Fix toast messages not displaying

commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java, editor/src/main/com/mbrlabs/mundus/editor/input/FreeCamController.kt, editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainSmoothTab.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/TerrainUtils.kt
Adds a new Terrain Brush for smoothing based on average heights of vertices within the brush radius. Also fixes the following issues
1. Terrain becomes un-editable by any brush when terrains global height is not zero. 
2. isUnderTerrain method did not factor in world height
3. Cleaned up terrain code that was instantiating new Vectors in looped methods
4. Paint brush radius can be changed now using CTRL+Scroll wheel
https://user-images.githubusercontent.com/28971753/179386694-ac6e30ca-1375-45c0-90f5-ce482226b1cc.mp4
=> Terrain smoothing brush and height fixes

editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/events/FilesDroppedEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/BaseDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/SkyboxDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/importer/ImportTextureDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/FileChooserField.java, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/ImageChooserField.java
Adds the ability to drag and drop single + multiple textures into the import texture dialog. Also enables multi-selection for the image file chooser.
=> Add multi-texture import, drag and drop support

commons/src/main/com/mbrlabs/mundus/commons/assets/MaterialAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/TexCoordInfo.java, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/assets/ModelImporter.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/ModelComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/MaterialWidget.kt
UV attributes were not being imported into Mundus for GLTF models. This fixes that by getting and setting these values on GLTF import
```
public int uvIndex = 0;
public float offsetU = 0;
public float offsetV = 0;
public float scaleU = 1;
public float scaleV = 1;
public float rotationUV = 0;
```
NOTE: A known limitation of gdx-gltf PBR shaders is that it uses UV scale from one of the textures. Separate UV scale per texture type is not supported right now however, this PR adds UV scale props into each material type so that is could be supported later.
Now scaled UV will import into Mundus. Also adds new UI widgets to allow customizing these values.
=> Fix scaled UV on import, add widgets

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/SceneSettings.java, commons/src/main/com/mbrlabs/mundus/commons/dto/SceneDTO.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/WaterComponent.java, commons/src/main/com/mbrlabs/mundus/commons/utils/ModelUtils.java, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/converter/SceneConverter.java, editor/src/main/com/mbrlabs/mundus/editor/tools/TranslateTool.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/settings/PerformanceSettingsTable.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/settings/SettingsDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/TransformWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/WaterWidget.kt, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/SceneConverter.java
Adds frustum culling for Models, Terrains, and Water to help with performance. If shadows are enabled, the shadow map camera frustum is also factored in for culling. Also adds a SceneSettings object and water settings were moved into that object. Also adds a performance settings area for frustum culling toggling per scene.
Observe profiler stats with objects in view:
Turning the camera away and observe profiler stats with frustum culling enabled
=> Add frustum culling

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/Mundus.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectContext.java, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/preferences/MundusPreferencesManager.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/UI.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/PersistingFileChooser.kt
Extends FileChooser and makes Preferences manager a bit more reusable. Now there is a global preferences and a project preferences file. Project preferences file will now store last opened directory from a file chooser. On project loading that directory is read from preferences and applied. Projects preferences manager lives within project context
FileChooser.setDefaultPrefsName was also moved as it was not being called before file chooser initialization and thus the preferences key was not being used.
=> Track last open directory for FileChooser per project

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/utils/DebugRenderer.java, commons/src/main/com/mbrlabs/mundus/commons/utils/Renderer.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectContext.java, editor/src/main/com/mbrlabs/mundus/editor/input/ShortcutController.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/UI.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/KeyboardShortcutsDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/WindowMenu.kt
Adds a debug render mode (shows model/terrain/water's bounds) and a wire frame mode.
Also adds shortcut keys dialog
=> Debug/Wireframe render modes and Keyboard Shortcuts window

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/assets/ModelAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/TerrainAsset.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/events/AssetDeletedEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AssetCleanUpDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/assets/AssetPickerDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/LogBar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/ProfilingBar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/AssetInspector.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/Inspector.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/assets/UsedByAssetInspectorWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/MundusMenuBar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/ToolsMenu.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/AutoFocusListView.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/AutoFocusScrollPane.kt
1. Adds a tool to detect and delete unused assets as deleting assets manually is painful. Can be activated by going to Tools -> Asset Clean Up in the top bar.
2. Adds a new Usages Inspector widget when clicking on assets in the asset dock which shows all uses of the selected asset in other assets and scenes
3. Update most scroll panes to use new auto focusing scroll pane which detects mouse enter and gives focus to scroll pane without requiring a click.
=> Unused Assets Tool

editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/ui/UI.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/tools/AssetCleanUpDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/tools/DebugRenderDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/ToolsMenu.kt
Adds a way to toggle existing debug rendering modes via the UI underneath the Tools file option.
Also added a fix to the async load process for fresh installs of Mundus with no existing projects
=> Dialog window for debug rendering

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/dto/ModelComponentDTO.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/ModelCacheManager.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/ModelCacheable.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/converter/ModelComponentConverter.java, editor/src/main/com/mbrlabs/mundus/editor/history/commands/DeleteCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableModelComponent.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/ModelComponentWidget.kt, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/ModelComponentConverter.java
Adds some basic model caching capabilities. Introduces new ModelCacheManager class within a Scene for maintaining and building/rebuilding the cache. Static objects with Model Components can enable model caching by checking a new box .
=> Model caching

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/MundusToolbar.kt
There is also `Import texture` button, not just `Import 3D Model` button. So I think the `Import` tooltip would be better.
It also contains `Create material` button, what is not import. Maybe it would be better somewhere else.
=> Changed Import model tooltip to Import

editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableModelComponent.java
Resolves issue with color picking only working on the first material when model has multiple materials.
=> Add colorpicking to each material

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/SceneMenu.kt
Currently we can add scene with empty name and I think it is not a good behavior. 
With this fix we can not add new scene with empty or blank name:
=> Scene name validation

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/core/scene/SceneManager.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/FileMenu.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/SceneMenu.kt
Added submenus to scene menu. 
* `Open` - Opens the selected scene
* `Delete` - Deletes the scene
The `Delete` button is disabled on the current selected scene:
After clicked to the `Delete` button then the application shows a confirmation modal:
=> Scene deleting

editor/src/main/com/mbrlabs/mundus/editor/input/FreeCamController.kt
This PR resolves Gimbal Lock (camera spasms) when looking directly up or down with the editor camera. Solution from https://github.com/libgdx/libgdx/issues/4023
=> Fix gimbal lock on editor camera

commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, gdx-runtime/CHANGES
A added two methods:
- addGameObject(ModelInstance, Vector3)
- addGameObject(Model, Vector3)
into SceneGraph.
There methods can add external model object into the scene graph.
https://user-images.githubusercontent.com/1684274/197379088-ea7a6be4-5147-4074-987b-469eeeb474e4.mp4
Test code:
```
private Mundus mundus;
private Scene scene;
private FirstPersonCameraController controller;
@Override
public void create () {
mundus = new Mundus(Gdx.files.internal("mundus"));
mundus.getAssetManager().getGdxAssetManager().load("uploads_files_2305968.gltf", SceneAsset.class);
mundus.getAssetManager().getGdxAssetManager().finishLoading();
SceneAsset sceneAsset = mundus.getAssetManager().getGdxAssetManager().get("uploads_files_2305968.gltf");
mundus.getAssetManager().maxNumBones = 30;
scene = …
```
=> Add external model object

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/EditorScene.java, editor/src/main/com/mbrlabs/mundus/editor/core/converter/TerrainComponentConverter.java, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableTerrainComponent.java, editor/src/main/com/mbrlabs/mundus/editor/tools/SelectionTool.java, editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/assets/TerrainAssetInspectorWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainBrushGrid.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainGenTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainPaintTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainSettingsTab.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/ObjExporter.java, editor/src/main/com/mbrlabs/mundus/editor/utils/TerrainUtils.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/TestUtils.kt, gdx-runtime/CHANGES, gdx-runtime/src/com/mbrlabs/mundus/runtime/SceneLoader.java, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/TerrainComponentConverter.java
The goal of this PR is to make Terrain Assets place-able and re-usable. Before, once a terrain asset was removed from a scene, it became unusable and could not be placed ever again. This PR adds a button when inspecting a terrain asset to add it to the scene (like models). The PR also makes it possible to reuse the same terrain asset in the same scene (like models). This required a somewhat large refactor of the Terrain class. The terrain class behaved like a ModelInstance, which made it difficult to be reusable. 
Instead the terrain class has been modified to behave more like a Model, and now TerrainComponent holds the ModelInstance reference (similar to ModelComponent) and transform data. Transform was removed from the Terrain class. This allows the asset/terrain to be reusable. Note …
=> Make terrain assets reusable

build.gradle, commons/src/main/com/mbrlabs/mundus/commons/shaders/custom-gdx-pbr.fs.glsl, commons/src/main/com/mbrlabs/mundus/commons/utils/ShaderUtils.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/FileHandleWithDependencies.kt
Upgrades gdx-gltf version to latest stable version. Also fixes a bug where models that use textures with spaces in the file name would not load.
=> Upgrade gdx-gltf to 2.1.0

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt
Adds a button to open/view the directory the asset file is in. Tested on Windows, not able to test on linux at this time.
=> Add an Open asset directory button

commons/src/main/com/mbrlabs/mundus/commons/assets/MaterialAsset.java, commons/src/main/com/mbrlabs/mundus/commons/assets/TexCoordInfo.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/events/MaterialDuplicatedEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableModelComponent.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/MaterialWidget.kt
Resolves #86 
Adds a button in the MaterialWidget shown in the object inspector to duplicate the current material so its properties can be changed without affecting all objects using the same material. The user is prompted to enter a name for the new material.
Edge cases checked:
* Material name already exists
* Material names are filenames so check there are no illegal characters
* Prevents file separators being added as filenames.
Other changes:
* Fixed a bug where when duplicating objects the materials ObjectMap in the `PickableModelComponent` and `ModelComponent` was assigned by reference rather than deep-copied so changing the materials on a duplicate item changed all of its duplicates materials too.
Usage:
1. To set up the scenario I have duplicated the Ship. In the MaterialWidget …
=> Ability to duplicate materials

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/importer/ImportModelDialog.kt
When importing models, they are first moved into a temporary directory for fbx conversion, if needed. However, they are never deleted on import completion or if the import was cancelled. On my own machine the mundus temp directory had 1 gigabyte of temp data. 
I have not added code to retroactively delete existing temp files, but this code will delete the temporary model files on either window close or import completion going forward.
Also adds code to 'reset' the import dialog, otherwise the import dialog when reopened shows the previous imported model.
Have not been able to test on Linux yet as my WSL is not working for some reason.
=> Handle deleting of temp model files

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/converter/SceneConverter.java, editor/src/main/com/mbrlabs/mundus/editor/tools/picker/ToolHandlePicker.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/settings/CameraSettingsTable.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/RenderWidget.java, editor/src/main/com/mbrlabs/mundus/editor/utils/Compass.kt, gdx-runtime/CHANGES, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/SceneConverter.java
Updates the Scene.java camera to be a Camera instead of PerspectiveCamera. This allows runtime applications to change the camera to an Orthographic (or any other subclass of camera) if they wanted. No actual support added for Orthographic viewing within the editor it's self.
=> Have Scene Camera use base Camera class

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/BaseBrushTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainBrushGrid.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainFlattenTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainPaintTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainSmoothTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainUpDownTab.kt
I think better if we show the brush selection on the UI. And if the User click to other tab then the selection will be clear.
Before:
https://user-images.githubusercontent.com/1684274/220960525-670b9d1f-58ac-4b32-98a6-53736a2a33db.mp4
After:
https://user-images.githubusercontent.com/1684274/220960568-735c1860-9d66-4110-bb82-201d021d5dff.mp4
=> Show brush selection

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/MundusMenuBar.kt
If I select a model then the menubar size changes. The inspector tries to use the max height if the scrollbar is visible and the menubar will smaller. I set fix size for icon, so inspector doesn't change the size. 
I've tested on Linux.
Before:
[before.webm](https://user-images.githubusercontent.com/1684274/221294258-9effde9f-5f02-4095-9522-5e5ebee71a66.webm)
After fix:
[after.webm](https://user-images.githubusercontent.com/1684274/221294350-32b5d26b-2d40-40f5-8b88-3de1e116f622.webm)
=> Fix menu icon size

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/Outline.kt
I've found a selection bug in the outline. If I select terrain and select a brush tool and select another game object in the outline then the outline doesn't reset selection tool.
Before fix:
After fix:
=> Set default tool if select other game object

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/skybox/Skybox.java
This PR is for someone using the Mundus runtime, who does not want to render a skybox, or wants to disable/enable skybox rendering whenever they want in their game.
edit: to disable/enable skybox rendering in the scene when ever they want.
=> Add boolean active to Skybox class in commons.

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/Main.kt
This PR sets the Editor to use 8 samples of MSAA by default. It can be disabled by program arguments for users with lower end hardware. This also sets the depth buffer to be 24 whereas the default was 16 (libGDX default) before.
=> Enable MSAA by default, with CLI to disable

commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java
Fix for @antzGames's [comment](https://github.com/JamesTKhan/Mundus/pull/153#issuecomment-1520380633).
So we should scale the height with y scale value because currently the height value is the local height value, not the height in the world.
=> Return with world height instead of local height

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/utils/ModelUtils.java, gdx-runtime/CHANGES
Frustum check only added models center to the instance world position. This did not take into account rotations or scale properly. Updated frustum check to account for rotations. This issue is most noticeable with things like Terrain / water. 
@Dgzt can you test this when when you have a moment?
=> Fix Frustum culling with rotations

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/IdentifierWidget.kt
This change fixes if rename a game object in inspector (Identifier widget) the new name won't be in the Outline.
=> Show new game object name in Outline

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, gdx-runtime/CHANGES
Attempt to fix water reflections when camera is rotated other then pitch. Previously they would break.
=> Fix reflections on cam rotation

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java
Minor optimization to frustum cull checks. Frustum cull checks use 1 to 2  matrix multiplications every time. With this change, items that are not culled will only be checked every 15 frames instead of every frame. Also, added a return statement to modelCache culling logic that seems to be missing.
=> Reduce cull check matrix calcs

commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/events/ToolActivatedEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/tools/SelectionTool.java, editor/src/main/com/mbrlabs/mundus/editor/tools/ToolManager.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/UI.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/MundusToolbar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddComponentDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/DockBar.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/Inspector.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/IdentifierWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/TransformWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/BaseBrushTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainBrushGrid.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainPaintTab.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/Outline.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/TextureGrid.java, gdx-runtime/CHANGES
Currently if select a game object and press ESC key then the selection is clearing but the game object is selected in the Outline and see it's properties on Inspector. And if change a property in Inspector then it doesn't change on game object.
Before fix:
After fix:
If selected a brush tool on terrain then the previous tool still selected on the toolbar, but not this tool the active. It's misleading. After fix, the previous selected tool (any tool from toolbar, like translate tool, rotate tool, etc) will be deselected.
Before fix:
After fix:
Currently If selected a terrain brush tool and pressing ESC key then brush tool will be deactivated but the previous tool on toolbar still visible as active but it doesn't active, the wireframe doesn't visible. After fix after pressing ESC key then …
=> Tool and game object selection bugfixes

commons/src/main/com/mbrlabs/mundus/commons/dto/CustomPropertiesComponentDTO.java, commons/src/main/com/mbrlabs/mundus/commons/dto/GameObjectDTO.java, commons/src/main/com/mbrlabs/mundus/commons/mapper/CustomPropertiesComponentConverter.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/Component.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CustomPropertiesComponent.java, commons/src/main/commons.gwt.xml, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/converter/GameObjectConverter.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddComponentDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/GameObjectInspector.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/CustomPropertiesWidget.kt, gdx-runtime/CHANGES, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/GameObjectConverter.java
Implementation of [#150](https://github.com/JamesTKhan/Mundus/issues/150) feature request.
1) Click to the **Add component** button on a game object in inspector:
2) Select **CUSTOM PROPERTIES** item in the dropdown and click to the **Add component** button:
3) See the new custom properties component in inspector:
You can remove added custom properties component with the **X** button on the left side. And you can collapse this widget with **ˇ** button on the right side.
4) Can add new custom property key-value pair with **Add** button. It will create an empty key-value pair and can change their texts. 
5) There is only one restriction: can not be 2 keys with same text. In this case if the user click out from the key field the key's value change back to the previous valid value.
```java …
```
=> Custom properties for game objects

commons/src/main/com/mbrlabs/mundus/commons/shaders/terrain.uber.frag.glsl
While working on triplanar mapping I made some other changes to how normals for splat maps get blended. This shouldn't result in a visual change. Putting this PR in first to try and keep things cleaner.
=> Update Terrain Normal blending

editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt
A small fix for helper lines. Currently helper line function doesn't check helper lines status (enabled/disabled) when a terrain added and tries to add helper line object.
How to reproduce this bug:
1) Check that the helper lines function is disabled
2) Add a new terrain
3) See error in console
=> Fix helper line if added terrain when helper lines is disabled

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
Currently if deleting the selected game object then the Inspector doesn't clear itself.
Before fix:
After fix:
=> Clear selection if selected game object deleted

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddComponentDialog.kt
I think component name text is better then enum value in dropdown.
What do you think?
=> Component text instead of enum value on component dialog

commons/src/main/com/mbrlabs/mundus/commons/shaders/terrain.uber.frag.glsl, editor/CHANGES, gdx-runtime/CHANGES
Seems I could fix #183 . 
Before:
After:
=> Fix for transparent layer in texture splatting for the terrain texture #183

commons/src/main/com/mbrlabs/mundus/commons/Scene.java
In Scene we call batch.begin and batch.end often. This is fine from my  understanding, but I see that we can reduce the amount of times we call end. This will reduce how often we are flushing the batch. It may provide a small performance boost as we are executing less code by batching more of the rendering together. Thoughts?
=> Reduce batch flushes

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/generation/HeightmapTab.kt
Added a `minMax` field to `HeightMapTab.kt`
If left blank, or set to zero (which would generate a flat terrain) then a default value positive 100 is set.
If user sets the minMax value to negative then the heightmap is inverted.
I think the `Terraformer` class does not allow negative `minHeight` so that is why I only implemented one min/max field.
See https://github.com/JamesTKhan/Mundus/issues/174#issuecomment-1567232389 for more info and screenshots.
=> Max height for heightmap

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, editor/src/main/com/mbrlabs/mundus/editor/core/EditorScene.java, gdx-runtime/CHANGES
This is the first GL30 addition to Mundus. If GL30 is enabled/available, water refraction FBO uses MRT to attach a depth texture. This removes the need for an additional depth render pass for water refractions meaning less vertices, draw calls, and shader switches per frame. 
GL20 behavior remains the same.
=> GL30: Use MRT FBO for Water refractions on gl30

editor/src/main/com/mbrlabs/mundus/editor/events/EventBus.java, editor/src/test/java/com/mbrlabs/mundus/editor/events/EventBusTest.java
While working on a feature branch, I noticed a frame drop when posting evens often. I looked into the EventBus code for the first time and saw some areas for improvement. Every time an event was posted the EventBus searched through every subscriber, check that it is a subscriber, and then find and call the event method all of this using reflection was quite slow.
Updated the EventBus class to perform the reflection logic on Register instead, and then cache Event class -> Subscriber in a map for fast lookup on Post so now we only perform the slow operations once on register. Also cleaned up the class a bit and added more code documentation to the methods.
Additionally, added a junit test for the EventBus.
In a quick performance test of posting 100 events with 100 subscribers, the old code …
=> Fix EventBus Performance issues

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/history/commands/DeleteCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
Currently if we remove a terrain and after enable the helper lines then the removed terrain's helper lines will be visible.
Before fix:
After fix:
=> Removed terrain in helper lines fix

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/GameObjectInspector.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/Inspector.kt
If I delete a game object what contains light component and select an another game object (what doesn't contain light component) and undo deleted game object then the light component will be show on the selected game object.
Before fix:
After fix:
=> Undo removed light fix

build.gradle, commons/src/main/com/mbrlabs/mundus/commons/Scene.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/profiling/MundusGL30Interceptor.java, gdx-runtime/CHANGES
Upgrade to libGDX 1.12.0. With that I also fixed an invalid value being used in GL30 MRT FBO construction. After testing many variations, one of the reasons I was looking forward to WebGL2 is currently useless. 
Using the same code for MRT FBO with 24bit Depth on WebGL2 vs Desktop, there are precision issues on WebGL2 with the water rendering. On desktop this is not happening. Unknown why at this time, so Water refractions will not use MRT FBO's on WebGL2 for the time being as it should not hold back the update to 1.12.0.
=> Upgrade libGDX to 1.12.0

editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLineShape.kt, editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt, editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HexagonHelperLineShape.kt, editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/RectangleHelperLineShape.kt, editor/src/main/com/mbrlabs/mundus/editor/events/TerrainNewNeighborEvent.kt, editor/src/main/com/mbrlabs/mundus/editor/history/commands/TerrainNeighborCommand.kt
Helper lines support for terrain chunks.
Left to do:
=> Helper lines support for terrain chunks

editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java
Fix several issues around how Mundus loads projects. Previously Mundus crashes if the registry is deleted but the default project is still present, that is now fixed. Mundus also crashed if previously opened project was deleted. That is also fixed.
Scenarios tested and passing:
- No registry, no default project
- Registry, no default project
- No registry, has default project already
=> Fix issues on loading projects

commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SimpleNode.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/LightComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/Outline.kt
Several things here, primarily adding the SimpleNode enhancement for the issue that I opened a while back.
1. Add dirty transform flag to SimpleNode to improve efficiency of SimpleNode. Every time getTransform, getPosition, getRotation and getScaled are called on a GameObject, the objects world transform is recalculated and this becomes worse the more nested children you have. Now the transform is cached and only updated when flagged as dirty.
2. Fix object scale not marked as changed for children, breaking frustum culling on children with scaled parents.
3. Translating children terrains parents caused them to not update visually. That is fixed now.
4. I revamped some of the conversion code in outline for drag and drop of children as it was behaving strange and compounding the objects …
=> SimpleNode efficiency, cache transforms

build.gradle, editor/CHANGES
The LibGDX has updated in [this](https://github.com/JamesTKhan/Mundus/pull/204) PR, so I've updated VisUI to 1.5.2, because the current version of VisUI (1.5.0) uses LibGDX 1.10.0.
=> Update Visui to 1.5.2

build.gradle, editor/CHANGES
This PR is pair of [this](https://github.com/JamesTKhan/Mundus/pull/209) PR. Updates KTX to 1.12.0 because the current KTX uses libGDX version 1.10.0. In this PR I've updated Kotlin also because min 1.9.0 required for KTX 1.12.0.
=> Update KTX to 1.12.0

commons/src/main/com/mbrlabs/mundus/commons/scene3d/Node.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SimpleNode.java
Add new convenience method for getting a GameObject/SimpleNode/Node's current forward direction.
=> Add get forward direction method

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/preferences/MundusPreferencesManager.kt, editor/src/main/com/mbrlabs/mundus/editor/tools/SelectionTool.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/settings/AppearanceSettingsTable.kt
The default line width is 1.0 and it is too thin sometimes.
There are 3 types of line:
- Object selection
- Wireframe mode
- Helper lines
The width of these lines can be changed in the settings menu:
=> Adjustable lines width

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/tools/RotateTool.java, editor/src/main/com/mbrlabs/mundus/editor/tools/ScaleTool.java, editor/src/main/com/mbrlabs/mundus/editor/tools/TranslateTool.java
Per tool scaling did not rebase abstracts.
=> Scale transform tools on act()

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/utils/DebugRenderer.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/Editor.kt, editor/src/main/com/mbrlabs/mundus/editor/Mundus.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectContext.java, editor/src/main/com/mbrlabs/mundus/editor/input/ShortcutController.kt, editor/src/main/com/mbrlabs/mundus/editor/preferences/MundusPreferencesManager.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/tools/DebugRenderDialog.kt
libGDX has something called OrientedBoundingBox. This fixes the bounding boxes not rendering rotations properly by using models/modelbatch + Oriented Bounding Box for the debug lines instead of shape renderer
The added bonus is that now all CullableComponents have actual dedicated Oriented bounding boxes, and this could be used for basic collision detection as well in the runtime as well. The downfall is slightly more memory overhead.
Another addition is the option to render debug lines with or without depth. 
Also added preferences saving for debug renderer options so user preference will persist on editor close
https://github.com/JamesTKhan/Mundus/assets/28971753/63b13523-a9b3-4eb2-a25b-62bd2235586d
https://github.com/JamesTKhan/Mundus/assets/28971753/7b55f849-e760-412f-ba26-17a51f4690f4 …
=> Add OBB to cullables

commons/src/main/com/mbrlabs/mundus/commons/scene3d/SimpleNode.java, commons/src/main/com/mbrlabs/mundus/commons/utils/Pools.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/history/commands/MultiCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
Adds two new actions on the Outline pane for GameObjects and several minor changes.
"Align Camera to Object" - Sets the cameras position and direction, to the objects position and direction
"Align Object to Camera" - Sets the objects position and rotation to match the cameras position and direction
Align Object to Camera supports Undo/Redo.
One good use case is if you are using GameObjects to represent camera locations, either for cinematic purposes or other reasons (fixed camera style games), you can set your camera in a good spot, then align a GameObject to this spot.
Other changes:
- Added Quaternion and Matrix4 pools
- Added MultiCommand.kt, a wrapper that can execute multiple history Commands in one Undo/Redo action (Ex. Change position and rotation at same time)
- Add a fix to …
=> Align To Camera / Align to Object actions

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/LightComponent.java, editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/LightWidget.kt, gdx-runtime/CHANGES
Breaking Change with Spotlights. Spotlights now use the forward direction of the GameObject they are attached to. Previously they used sliders to change up/down left/right direction independently of the game object, and if you rotate the game object, it had NO effect on the spotlights rotation.
This was not intuitive, now it easier to control direction by simply rotating the game object. 
TLDR: Spotlight rotation is now controlled by GameObject rotation.
https://github.com/JamesTKhan/Mundus/assets/28971753/7066a3b5-b2c9-468f-a009-2ee500a4dfb7
=> Spotlight rotations use GameObjects rotation

editor/src/main/com/mbrlabs/mundus/editor/history/commands/GameObjectActiveCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/IdentifierWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
Undo/Redo commands have not been kept up as good as they probably should have been. I will be making more actions undo-able as I come across them. 
When a GameObject is activated or deactivated by UI, it is now added to command history and you can redo/undo the action.
=> Allow redo/undo on GameObject active change

commons/src/main/com/mbrlabs/mundus/commons/scene3d/DirtyListener.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/DirtyObservable.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SimpleNode.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/LightComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/ModelComponent.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableLightComponent.java
Discovered while working on game jam that the current approach in components to check isDirty, is not sufficient, as it entirely depends on the order of method executions. If getTransform() is called before the update of the Component, isDirty can be false by the time the component updates. In my use case CullableComponents OrientedBoundingBox was out of sync with the actual objects position as the isDirty() check was never true.
Now instead this bullet proofs the problem by adding DirtyObservable and DirtyListener, each SimpleNode/GameObject can have listeners subscribed to a onDirty event. 
Components (as applicable) now subscribe to this event so that they can perform translation updates when the parent GameObject is dirty.
=> Add and use DirtyListener interface

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/dto/AssetUsageDTO.java, commons/src/main/com/mbrlabs/mundus/commons/dto/GameObjectDTO.java, commons/src/main/com/mbrlabs/mundus/commons/dto/ModelComponentDTO.java, commons/src/main/com/mbrlabs/mundus/commons/dto/TerrainComponentDTO.java, commons/src/main/com/mbrlabs/mundus/commons/dto/WaterComponentDTO.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/scene3d/components/PickableLightComponent.java
I noticed during September Jam with a slightly larger project (150 assets) the Asset Clean Up was very slow, to the point of not being usable. 
This is because when I coded it, it wasn't very efficient. It loaded full Scene objects and then initialized the Scenes GameObjects (Components and all, meaning Models got instantiated and everything).
This was bad (longer than 30 seconds  on jam project). I have expanded the AssetUsage to add AssetUsageDTO. Now GameObjectDTO's can return if they use an asset or not. This is exponentially faster than the previous approach. On my jam project the search is responsive now and completes in under a second.
Also, I removed the `boolean hasGLContext` argument from Scene. This was only needed for the AssetUsage purposes to load scenes off the main thread, …
=> Optimization fix in Asset Clean Up system

commons/src/main/com/mbrlabs/mundus/commons/Scene.java, commons/src/main/com/mbrlabs/mundus/commons/rendering/DefaultSceneRenderer.java, commons/src/main/com/mbrlabs/mundus/commons/rendering/SceneRenderer.java, commons/src/main/com/mbrlabs/mundus/commons/rendering/WaterRenderer.java, gdx-runtime/CHANGES
This is another step towards removing rendering logic from Scene and putting it into its own classes. Scene is responsible for too much right now.
The rendering logic is still kinda ugly but it's at least more separate now. The reason for this is to allow more flexibility to swap out things like shadow mapping techniques in the future. Breaking change for any one calling specific render methods other than the main ones, as they are now moved into the SceneRenderer class.
This will also make it easier for Runtime users to pass in their own custom SceneRenderer to allow more control over rendering.
=> Remove (most) rendering logic from Scene

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt
I've fixed that if the helper lines feature is enabled and deactivate a terrain then the helper lines of that terrain still visible.
Before fix:
After fix:
=> Deactivated terrain helper lines fix

commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, gdx-runtime/CHANGES
Two new methods into scene graph where can add external model/model instance to the scene graph. If call this methods then will create game objects as a child of given parent game object.
```java
addGameObject(final GameObject parentGO, final Model model, final Vector3 position)
addGameObject(final GameObject parentGO, final ModelInstance modelInstance, final Vector3 position)
```
=> Two methods in scene graph where can add game object as child

commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java, commons/src/main/com/mbrlabs/mundus/commons/utils/ModelUtils.java, editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java, editor/src/main/com/mbrlabs/mundus/editor/history/commands/DeleteCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/input/FreeCamController.kt, editor/src/main/com/mbrlabs/mundus/editor/tools/SelectionTool.java, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/CustomPropertiesWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/LightComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/ModelComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/TransformWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/WaterComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainComponentWidget.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/Outline.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt, gdx-runtime/CHANGES
Changed GameObject's **findComponentsByType** and **findComponentByType** methods from
```java
Array<Component> findComponentsByType(Array<Component>, Component.Type, boolean)
Component findComponentByType(Component.Type)
```
to
```java
<T extends Component> Array<T> findComponentsByType(Array<T>, Component.Type, boolean)
<T extends Component> T findComponentByType(Component.Type)
```
so can call these methods 
```java
Array<ModelComponent> components = gameObject.findComponentsByType(new Array<ModelComponent>(), Component.Type.MODEL, true)
ModelComponent component = gameObject.findComponentByType(Component.Type.MODEL)
```
instead of 
```java
Array<Component> components = gameObject.findComponentsByType(new Array<Component>(), Component.Type.MODEL, true)
ModelComponent component = …
```
=> Generic find component methods

gdx-runtime/src/com/mbrlabs/mundus/runtime/Mundus.java
If I add model what has bones then I get "_too many bones: 43, max configured: 0_" exception, so I should set bones in this configs, so I added these methods into runtime:
```java
Scene loadScene(String name, PBRShaderConfig config, DepthShader.Config depthConfig)
Scene loadScene(String name, PBRShaderConfig config, DepthShader.Config depthConfig, RenderableSorter renderableSorter)
```
=> Custom depth shader config in rurntime

editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt
Currently if helper lines is not enabled and activate a deactivated terrain then there is an exception.
```java
Caused by: java.lang.IllegalArgumentException: Step must be positive, was: -1.
at kotlin.ranges.RangesKt__RangesKt.checkStepIsPositive(Ranges.kt:274)
at kotlin.ranges.RangesKt___RangesKt.step(_Ranges.kt:966)
at com.mbrlabs.mundus.editor.core.helperlines.HexagonHelperLineShape.calculate(HexagonHelperLineShape.kt:137)
at com.mbrlabs.mundus.editor.core.helperlines.HexagonHelperLineShape.calculateIndicesNum(HexagonHelperLineShape.kt:44)
at com.mbrlabs.mundus.editor.core.helperlines.HelperLineShape.<init>(HelperLineShape.kt:66)
at com.mbrlabs.mundus.editor.core.helperlines.HexagonHelperLineShape.<init>(HexagonHelperLineShape.kt:27)
at …
```
=> Terrain activation if helper lines disabled fix

editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/history/commands/SortChildrenCommand.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
If a game object has children then the Sort children menu enabled and it sorts the children alphabetically.
=> Game object children sorting action menu

editor/src/main/com/mbrlabs/mundus/editor/input/FreeCamController.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/StatusBar.kt
Not sure if this counts but I think it can serve as a basic indicator for the selected movement speed. It also guides the user because only valid options remain clickable.
[Screencast from 2023-11-10 18-01-50.webm](https://github.com/JamesTKhan/Mundus/assets/150134091/b975775b-3ac9-49c6-92e0-f0e068755fb1)
=> Disable button on camera movement speed selection (#263)

commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddWaterDialog.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/Outline.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt, gdx-runtime/CHANGES, gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/SceneConverter.java
This PR contains some fixes:
1) If we move the mouse to a game object in Outline and click to Add water or Add terrain then it will be added as child game object.
2) If we create a water at root in Outline and move it into a game object as a child game object then it will be rendered.
3) There is the `findComponentsByType(Array<Component> out, Component.Type type, boolean includeChilds)` method in GameObject class and it's javadoc says that if the **includeChilds** variable is true then it searches in children too, but in this case this method doesn't search in the current game object, only in children. So with this fixes if **recursive** variable is true then it will search in the current game object and recursively too. Added this changes into runtime's CHANGES file as braking changes. …
=> Add water and terrain as child game object

editor/src/main/com/mbrlabs/mundus/editor/Editor.kt
I tried to restore the intended behaviour. A default project should now be opened/created as expected.
=> Fix crash when last project is deleted

editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectManager.java
The main problem i found should be solved, but in case something goes wrong the user at least gets a notification.
Unfortunately when loading goes wrong there are no asset visible in the ui even though the editor does not crash any more. At least the user gets a hint on how to fix the issue.
=> Handle asset import errors

commons/src/main/com/mbrlabs/mundus/commons/shadows/MundusDirectionalShadowLight.java
Fixes a crash with using libGDX-screenmanager library by using NestableFrameBuffer for our ShadowMap all the time, as Screenmanager requires the applications to use NestableFrameBuffer instead of FrameBuffer.
=> Fix crash when using libgdx-screenmanager library

commons/src/main/com/mbrlabs/mundus/commons/assets/AssetManager.java, editor/CHANGES, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt, editor/src/main/com/mbrlabs/mundus/editor/assets/EditorModelAsset.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dock/assets/AssetsDock.kt, editor/src/main/com/mbrlabs/mundus/editor/utils/ThumbnailGenerator.kt
Thumbnail visible for models in Assets Dock.
Creates thumbnail in these cases.
- Import 3D model into project
- Mundus editor startup
=> Model thumbnail in Assets Dock

editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/TerrainTextureLayerWidget.kt
On the `terrain_chunks` branch if I select a terrain and click to the `Paint` tab and click to the `Edit` button on the terrain layer widget then Editor opens terrain layer widget on Inspector but the `Edit` button still visible and does nothing.
=> Hide Edit button on terrain layer asset edit widget

commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/CullableComponent.java, editor/CHANGES
Added `checkShadowDuringFrustumCulling` option into CullableComponent to enable/disable shadow checking during frustum culling.
=> Check shadow during frustum culling setting

editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainChunksDialog.kt
The dialog generates LoD for terrain if the checkbox is not selected.
=> Doesn't generate LoD if it's checkbox is not enabled

editor/src/main/com/mbrlabs/mundus/editor/tools/ScaleTool.java
This is the fix for #284  bug. 
I don't know why was there the terrain checking in the scale tool, so I removed it. Now the scaling works perfectly with terrain too.
=> Terrain rotation tool fix

build.gradle, commons/src/main/com/mbrlabs/mundus/commons/shaders/pbr/material.glsl, commons/src/main/com/mbrlabs/mundus/commons/shaders/pbr/pbr.fs.glsl, editor/CHANGES, gdx-runtime/CHANGES
The triplanar fix for gdx-gltf upgrade PR. 
This is the exception if I use triplanar terrain with gdx-gltf-upgrade branch:
```
[11:29][Trace][Outline] Project changed. Building scene graph.
[11:29][Fatal][Log] com.badlogic.gdx.utils.GdxRuntimeException: Shader compilation failed:
Fragment shader:
0:385(13): error: v_position' undeclared
0:385(13): error: type mismatch
0:385(13): error: operands to arithmetic operators must be numeric
0:386(13): error: v_position' undeclared
0:386(13): error: type mismatch
0:386(13): error: operands to arithmetic operators must be numeric
0:387(13): error: v_position' undeclared
0:387(13): error: type mismatch
0:387(13): error: operands to arithmetic operators must be numeric
0:390(37): warning: uvX' used uninitialized
0:391(37): warning: uvY' used …
```
=> Triplanar terrain fix for gdx-gltf upgrade

commons/build.gradle, editor-commons/build.gradle, gdx-runtime/CHANGES, gdx-runtime/build.gradle, plugin-api/build.gradle
Hi,
I think we can increase source compatibility to 1.8. The default method feature in plugin api would be useful. 
The libGDX [wiki page](https://libgdx.com/wiki/articles/java-development-kit-selection#versions) says the 1.8 jdk version useable on all platfom, only the android 5/6 support will drop, but these are very [old android versions](https://en.wikipedia.org/wiki/Android_version_history).
=> Source compatibility to 1.8

build.gradle, editor/src/main/com/mbrlabs/mundus/editor/Main.kt, editor/src/main/com/mbrlabs/mundus/editor/ui/gizmos/LightGizmo.kt
I've updated the libGDX to 1.13.0.
- The `SharedLibraryLoader.isMac` is deprecated, so I've changed to `SharedLibraryLoader.os == Os.MacOsX`, apidoc says this.
- I've removed the unnecessary `lateinit` keyword in LightGizmo class.
Now there is no warning message during building.
=> Update libGDX to 1.13.0

commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java, gdx-runtime/CHANGES
Optimized findChildrenByComponent and findChildrenByTag methods to avoid creating a new array on each call. Now, if a pre-existing array is provided, results are added to it, reducing object creation and improving performance.
Add 
- findChildrenByComponent(Component.Type, Array<GameObject>) and 
- findChildrenByTag(String, Array<GameObject>) methods into GameObject file
=> Optimalization
