JamesTKhan/Mundus

- editor/src/main/com/mbrlabs/mundus/editor/tools/ToolManager.java
This PR can be controversial but for me is a must-have.
Keeps the current selection if the tool changes, it also works for hotkeys.
> QOL: Keep selection when changing tools

- build.gradle
- editor/src/main/com/mbrlabs/mundus/editor/exporter/Exporter.kt
- editor/src/test/java/com/mbrlabs/mundus/editor/exporter/ExporterTest.java
- editor/src/test/java/com/mbrlabs/mundus/editor/history/HistoryTest.java
Added simple test for empty scene and moved folders to keep maven package structure.
> Refactoring test folder

- build.gradle
Maybe a bit faster the compile time with the newer kotlin version.
> Kotlin updated to 1.6.21

- commons/src/main/com/mbrlabs/mundus/commons/shaders/ModelShader.java
- commons/src/main/com/mbrlabs/mundus/commons/shaders/SkyboxShader.java
- commons/src/main/com/mbrlabs/mundus/commons/shaders/TerrainShader.java
These deprecated api calls caused warnings so I changed to nondeprecated api calls.
> bind method instead of deprecated begin and end methods of ShaderProgram

- editor/CHANGES
- editor/build.gradle
- editor/src/main/com/mbrlabs/mundus/editor/Main.kt
Catch up the changes file with all the latest changes
> Update changes and version for editor

- build.gradle
- editor/build.gradle
- gdx-runtime/build.gradle
- gradle/wrapper/gradle-wrapper.properties
I've updated the gradle version to 7.3.3. I've tested run, dist* and test tasks on editor and gdx-runtime.
> Updated gradle version to 7.3.3

- commons/src/main/com/mbrlabs/mundus/commons/shaders/WaterShader.java
- commons/src/main/com/mbrlabs/mundus/commons/shaders/water.frag.glsl
- commons/src/main/com/mbrlabs/mundus/commons/shaders/water.vert.glsl
- editor/CHANGES
Fog added to water shader and now applies to water.
> Add fog to Water Shader

- commons/src/main/com/mbrlabs/mundus/commons/Scene.java
- commons/src/main/com/mbrlabs/mundus/commons/assets/SkyboxAsset.java
- commons/src/main/com/mbrlabs/mundus/commons/shaders/SkyboxShader.java
- commons/src/main/com/mbrlabs/mundus/commons/skybox/Skybox.java
- editor/src/main/com/mbrlabs/mundus/editor/assets/EditorAssetManager.kt
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/SkyboxDialog.kt
Add new settings and logic to rotate skyboxes with controllable speed.
https://user-images.githubusercontent.com/28971753/170808603-0baef1ea-05e6-4f00-ab79-e26bfa4516f7.mp4
> Skybox rotation

- editor/CHANGES
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/Outline.kt
Adds the ability to reorder items in the outline 
https://user-images.githubusercontent.com/28971753/182057443-4f1cf0e0-3cf2-4431-982b-c8457f035566.mp4
> Outline reordering

- commons/src/main/com/mbrlabs/mundus/commons/utils/MathUtils.java
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/SkyboxDialog.kt
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/importer/ImportTextureDialog.kt
- editor/src/main/com/mbrlabs/mundus/editor/ui/widgets/ImageChooserField.java
- editor/src/main/com/mbrlabs/mundus/editor/utils/ImageUtils.kt
Validate that images are square and power of two to prevent errors on skybox creation.
> Add more validations to Skybox image choosers

- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/menu/SceneMenu.kt
Saves new scene into project if the new scene added
> Save new scene into project when added

- editor/CHANGES
- editor/src/main/com/mbrlabs/mundus/editor/tools/ToolManager.java
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
I fixed the model selection after model delete.
https://user-images.githubusercontent.com/1684274/197872111-5999ce5c-db0c-4dbf-bf5a-3abe7d75aadf.mp4
> Model delete selection fix

- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainBrushGrid.kt
A small cleanup in TerrainBrushGrid class.
> Remove unused constructor

- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/KeyboardShortcutsDialog.kt
I've found that there is wrong info for look around shortcut, so I've fixed it.
> Fix look around shortcut info

- commons/src/main/com/mbrlabs/mundus/commons/dto/TerrainComponentDTO.java
- commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java
- commons/src/main/com/mbrlabs/mundus/commons/scene3d/components/TerrainComponent.java
- commons/src/main/com/mbrlabs/mundus/commons/terrain/Terrain.java
- editor/src/main/com/mbrlabs/mundus/editor/core/converter/GameObjectConverter.java
- editor/src/main/com/mbrlabs/mundus/editor/core/converter/TerrainComponentConverter.java
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainChunksDialog.kt
- gdx-runtime/src/com/mbrlabs/mundus/runtime/converter/GameObjectConverter.java
Implementation for neighbor terrain links.
> Setup neighbor terrains for generated terrain chunks

- commons/src/main/com/mbrlabs/mundus/commons/assets/AssetType.java
- commons/src/main/com/mbrlabs/mundus/commons/utils/DebugRenderer.java
- editor/CHANGES
- editor/src/main/com/mbrlabs/mundus/editor/Editor.kt
- editor/src/main/com/mbrlabs/mundus/editor/preferences/MundusPreferencesManager.kt
- editor/src/main/com/mbrlabs/mundus/editor/tools/SelectionTool.java
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/tools/DebugRenderDialog.kt
Working implementation for now. Need to cache arrow model in the future.
> Debug direction arrow

- editor/CHANGES
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
updated current name while renaming game object issue #243
> #243 When renaming an object, fill in current name

- editor/CHANGES
- editor/src/main/com/mbrlabs/mundus/editor/tools/ToolManager.kt
- editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/StatusBar.kt
- editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/BaseBrushTab.kt
Editor shows the mouse position on statusbar if user uses a terrain brush tool.
> Mouse position on statusbar

- editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java
Fixes mouse position on statusbar on terrain_chunks branch.
Before fix:
https://github.com/JamesTKhan/Mundus/assets/1684274/9d43f3fe-a05b-42b1-83a3-711cba657793
After fix:
https://github.com/JamesTKhan/Mundus/assets/1684274/4a3aff50-f0c5-463e-b69a-e9f05fd5cdb9
> Mouse position fix on terrain_chunks branch

- commons/src/main/com/mbrlabs/mundus/commons/rendering/DefaultSceneRenderer.java
I've extracted a game object rendering logic into a method, because in this case I can add custom logic into this metho like this:
```java
public void renderSpecialModelsIntoFBO() {
renderOnlyCertainModel = true;
beginFBO();
scene.batch.begin(scene.cam);
renderComponents(scene, scene.batch, scene.sceneGraph.getRoot(), null, false);
scene.batch.end();
endFBO();
renderFBO();
renderOnlyCertainModel = false;
}
@Override
protected void renderComponent(Scene scene, ModelBatch batch, GameObject gameObject, Shader shader, boolean isDepthPass) {
if (renderOnlyCertainModel && (gameObject.getTags() == null) || !renderOnlyCertainModel && (gameObject.getTags() != null && gameObject.getTags().contains("CERTAIN_MODEL_TAG", true))) {
return;
}
super.renderComponent(scene, batch, gameObject, shader, …
```
> Extract game object rendering into a method

- commons/src/main/com/mbrlabs/mundus/commons/shaders/MundusPBRShader.java
- commons/src/main/com/mbrlabs/mundus/commons/shaders/pbr/pbr.fs.glsl
I've added dynamic loops for lights in pbr shader like in water and terrain shaders. With this I got 3x performance boost.
> Dynamic loop for lights in pbr shader
